### ISSUE TITLE
Is handling of RGB Images Covered for np arrays?

### ISSUE THREAD

**Issue by khanfarhan10** [lobantseff/segmentation-mask-overlay#1]
@lobantseff 

I find AssertionError: Supported only grayscale numpy arrays.

Is handling of RGB Images Covered in the specific case of numpy arrays?

**Comment by lobantseff** [comment]
Hi @khanfarhan10 

Yes. So far are only grayscale images supported, since I'm mostly use this library for medical imaging tasks. If you would like to add RGB, please feel free to propose a PR.

**Comment by lobantseff** [comment]
Hi @khanfarhan10,

I'm updating and simplifying the interface in [`move-to-cv2`](https://github.com/lobantseff/segmentation-mask-overlay/tree/move-to-cv2) branch. It also supports RGB numpy arrays now. If you're still interested, you can check it out! Performace also increased from 0.2 s with PIL-based in-paintings to 0.01 s with opencv addWeighted method.

**Comment by lobantseff** [comment]
See the comment above
